USE AIRBNB;

SELECT USER.USER_ID, USER.FIRST_NAME,USER.LAST_NAME, COUNT(BOOKING.BOOKING_ID) AS TOTAL_BOOKINGS FROM USER
LEFT JOIN BOOKING
ON USER.USER_ID= BOOKING.USER_ID
GROUP BY USER_ID;

SELECT USER_ID, RANK() OVER (ORDER BY COUNT(BOOKING_ID) DESC)AS RANKING FROM BOOKING
GROUP BY USER_ID
