USE AIRBNB;
SELECT BOOKING.BOOKING_ID, USER.USER_ID, USER.FIRST_NAME, USER.LAST_NAME FROM BOOKING
INNER JOIN USER
ON BOOKING.USER_ID = USER.USER_ID;

SELECT PROPERTY.PROPERTY_ID, PROPERTY.NAME, REVIEW.REVIEW_ID, REVIEW.COMMENT FROM PROPERTY
LEFT JOIN REVIEW 
ON PROPERTY.PROPERTY_ID = REVIEW.PROPERTY_ID;

SELECT * FROM USER
LEFT JOIN BOOKING
ON USER.USER_ID = BOOKING.USER_ID
UNION
SELECT * FROM USER
RIGHT JOIN BOOKING 
ON USER.USER_ID= BOOKING.USER_ID

