ALTER TABLE Booking RENAME TO Booking_old;

CREATE TABLE Booking (
    BOOKING_ID CHAR(36) PRIMARY KEY,
     PROPERTY_ID CHAR(36),
     USER_ID CHAR(36),
     START_DATE DATE NOT NULL,
     END_DATE DATE NOT NULL,
     TOTAL_PRICE DECIMAL(10,2) NOT NULL,
     STATUS ENUM('PENDING','CONFIRMED','CANCELLED') NOT NULL,
     CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     FOREIGN KEY(PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID),
     FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
) PARTITION BY RANGE (start_date);


CREATE TABLE Booking_2023 PARTITION OF Booking
    FOR VALUES FROM ('2023-01-01') TO ('2024-01-01');

CREATE TABLE Booking_2024 PARTITION OF Booking
    FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

INSERT INTO Booking (BOOKING_ID, PROPERTY_ID, USER_ID, START_DATE, END_DATE, TOTAL_PRICE, STATUS, CREATED_AT)
SELECT BOOKING_ID, PROPERTY_ID, USER_ID, START_DATE, END_DATE, TOTAL_PRICE, STATUS, CREATED_AT FROM Booking_old;

DROP TABLE Booking_old;
