EXPLAIN
SELECT 
BOOKING.BOOKING_ID,
USER.USER_ID,
USER.FIRST_NAME,
USER.LAST_NAME,
PROPERTY.PROPERTY_ID,
PROPERTY.HOST_ID,
PAYMENT.PAYMENT_ID
FROM BOOKING
JOIN USER ON BOOKING.USER_ID=USER.USER_ID
JOIN PROPERTY ON BOOKING.USER_ID=PROPERTY.PROPERTY_ID
LEFT JOIN PAYMENT ON PAYMENT.BOOKING_ID = BOOKING.BOOKING_ID
WHERE BOOKING.STATUS IS NOT NULL AND USER.EMAIL IS NOT NULL
