USE AIRBNB;
SELECT PROPERTY.NAME, PROPERTY.PROPERTY_ID FROM PROPERTY
WHERE (SELECT AVG(RATING) FROM REVIEW WHERE REVIEW.PROPERTY_ID = PROPERTY.PROPERTY_ID)>4.0;

SELECT USER_ID, FIRST_NAME, LAST_NAME FROM USER
WHERE (SELECT COUNT(*) FROM BOOKING WHERE BOOKING.USER_ID=USER.USER_ID)>3;


